# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-WarnDie
version:      0.05
version_from: lib/Log/WarnDie.pm
installdirs:  site
requires:
    Scalar::Util:                  1.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
